# Generated by Django 3.0.1 on 2021-02-12 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('coding', 'coding'), ('aptitude', 'aptitude')], max_length=200, null=True)),
                ('mark_multiplier', models.IntegerField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, choices=[('text', 'text'), ('image', 'image')], max_length=200, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('question_image_url', models.TextField(blank=True, null=True)),
                ('option1', models.TextField(blank=True, null=True)),
                ('option2', models.TextField(blank=True, null=True)),
                ('option3', models.TextField(blank=True, null=True)),
                ('option4', models.TextField(blank=True, null=True)),
                ('option5', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('answer_type', models.CharField(blank=True, choices=[('text', 'text'), ('choice', 'choice'), ('code', 'code')], max_length=200, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_choice', models.IntegerField(blank=True, null=True)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('test_case_1', models.TextField(blank=True, null=True)),
                ('test_case_2', models.TextField(blank=True, null=True)),
                ('test_case_3', models.TextField(blank=True, null=True)),
                ('test_case_4', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_questions_dict', models.TextField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestTakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('test_taker_category', models.CharField(blank=True, choices=[('email', 'email'), ('gridlex', 'gridlex')], max_length=200, null=True)),
                ('total_correct_answers', models.IntegerField(blank=True, default=0, null=True)),
                ('marks_result', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user_code', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Test')),
                ('test_taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.TestTakers')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_dict', models.TextField(blank=True, null=True)),
                ('test_start_time', models.DateTimeField(blank=True, null=True)),
                ('test_end_time', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Test')),
                ('test_taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.TestTakers')),
            ],
        ),
    ]
