# Generated by Django 3.0.1 on 2021-02-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210213_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='question_category',
        ),
    ]
